spring:
    profiles:
        active: dev
    data:
        mongodb:
            hosts:
              - localhost
            port: 32768
            database: test
            connectionsPerHost: 4
            readPreference: primaryPreferred